// lib/stripe.js — Stripe SDK wrapper
'use strict';

const Stripe = require('stripe');

function client() {
  return new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2024-09-30.acacia' });
}

async function createCheckoutSession({ sku, priceId, slotIso, name, email, calEventTypeId, baseUrl, mode }) {
  const stripe = client();
  const checkoutMode = mode === 'subscription' ? 'subscription' : 'payment';
  const params = {
    mode: checkoutMode,
    payment_method_types: ['card'],
    line_items: [{ price: priceId, quantity: 1 }],
    customer_email: email,
    allow_promotion_codes: true,
    metadata: {
      sku,
      slot_iso: slotIso || '',
      name,
      cal_event_type_id: String(calEventTypeId),
    },
    success_url: `${baseUrl}/thanks?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `${baseUrl}/book/${sku}?cancelled=1`,
  };
  if (checkoutMode === 'subscription') {
    // Stripe requires subscription_data.metadata for fields to land on the
    // Subscription object as well; mirror top-level metadata for parity.
    params.subscription_data = { metadata: params.metadata };
  } else {
    // One-off payments: auto-generate a finalised invoice PDF per payment so
    // the customer's success email carries both the receipt and an invoice.
    // Not registered for GST, so this is an invoice (not a tax invoice): ABN
    // shown as a custom field, GST status in the footer. Subscription-mode
    // invoices are generated by Stripe natively; the account default footer
    // covers those.
    params.invoice_creation = {
      enabled: true,
      invoice_data: {
        custom_fields: [{ name: 'ABN', value: '26 929 349 775' }],
        footer: 'No GST has been charged. Samuel Davis (Crads-AI) is not registered for GST; all amounts are GST-exclusive. This is an invoice, not a tax invoice.',
      },
    };
  }
  return stripe.checkout.sessions.create(params);
}

async function refundSession(sessionId) {
  const stripe = client();
  const session = await stripe.checkout.sessions.retrieve(sessionId);
  return stripe.refunds.create({
    payment_intent: session.payment_intent,
    metadata: { reason: 'race_loss_refund', stripe_session_id: sessionId },
  });
}

async function retrievePaymentIntent(piId) {
  const stripe = client();
  return stripe.paymentIntents.retrieve(piId);
}

async function updatePaymentIntentMetadata(piId, metadata) {
  const stripe = client();
  return stripe.paymentIntents.update(piId, { metadata });
}

function constructWebhookEvent(rawBody, signature) {
  const stripe = client();
  return stripe.webhooks.constructEvent(rawBody, signature, process.env.STRIPE_WEBHOOK_SECRET);
}

module.exports = { client, createCheckoutSession, refundSession, retrievePaymentIntent, updatePaymentIntentMetadata, constructWebhookEvent };
